%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
output_path: "~/output/"

cam0_calib: "left_3.yaml"
cam1_calib: "right_2.yaml"
image_width: 480
image_height: 640
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.999983894889441, -0.00440793301419765, 0.00357492493439619, -0.0550008207495751,
            -0.00287754519537642, -0.936717525267484, -0.350074274391033, -0.00975503300751726,
            0.00489179878907415, 0.350058349398071, -0.936715123354644, -0.00132148792060240,
            0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.999979779601092, 0.00321408971638084, 0.00548725944753664, 0.0550783336255521,
            0.00492884924818270, -0.936958488144209, -0.349405921443252, -0.00922981360292011,
            0.00401831233706562, 0.349425902190742, -0.936955384233501, -0.00137057350466811,
            0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 0

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.6561838800082605e-01          # accelerometer measurement noise standard deviation. 
gyr_n: 2.0783740699543856e-02         # gyroscope measurement noise standard deviation.     
acc_w: 2.2683907382254142e-04        # accelerometer bias random work noise standard deviation.  
gyr_w: 3.0074367448324271e-05       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
