%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
output_path: "~/output/"

cam0_calib: "left_3.yaml"
cam1_calib: "right_2.yaml"
image_width: 480
image_height: 640
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.9999694552499345, -0.0072152104539690, -0.0030048802395771, -0.0547172679127152,
        -0.0078106700124735, -0.9365808003025486, -0.3503646642265644, -0.0093313631711660,
        -0.0002863583515675, 0.3503774325534422, -0.9366085483040139, -0.0013837402167774,
        0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.9999736912567426, -0.0025745660226206, 0.0067814750725808, 0.0549386127463867,
        0.0000182946038590, -0.9339950344261914, -0.3572859853570025, -0.0091778737934729,
        0.0072537204021341, 0.3572767096761443, -0.9339704150899615, -0.0014666612065271,
        0.0000000000000000, 0.0000000000000000, 0.0000000000000000, 1.0000000000000000]
          

#Multiple thread support
multiple_thread: 0

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 2.3024034938032064e-02        # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 1.8613649544737473e-03        # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 1.8127675506531912e-04       # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.8798047943711679e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81         # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
use_loop: 0
show_compensate: 1

recall_ignore_recent_ct: 5 # how many frames we should skip that are recent (avoid matching to recent frames)
min_score: 0.01 # min score from dbow to try to loop closure with (0.015 default)
pnp_inflation: 10.0 # amount to inflate pnp ransac sigma by (10.0 default)

max_theta_diff: 170.0 # max orientation diff between keyframe and query frame (degrees)
max_pos_diff: 1.5 # max position diff between keyframe and query frame (meters)
min_loop_feat_num: 10 # minimum number of features needed to be matched between the keyframe and query frame

# keyframing parameters
kf_min_dist: 0.01 # meters, distance between keyframes
kf_min_dur: 0.01 # s, time duration between keyframes

brief_pattern_file: "D:/project/OpenVinsQinYaFei/out/build/support_files/brief_pattern.yml"
vocabulary_file: "D:/project/OpenVinsQinYaFei/out/build/support_files/brief_k10L6.bin"
